services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=orders

  nats:
    image: nats:latest
    restart: unless-stopped
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"

  order-service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    environment:
      - GRPC_URL=0.0.0.0:50051
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=orders
      - NATS_URL=nats://nats:4222
      - NATS_CLIENT_NAME=order-service
    ports:
      - "50051:50051"
    depends_on:
      - mongo
      - nats

  billing-service:
    build:
      context: .
      dockerfile: billing_service/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - ORDER_SERVICE_HOST=order-service:50051
      - PAYMENT_SUCCESS_RATE=0.85
      - NATS_CLIENT_NAME=billing-service
    depends_on:
      - order-service
      - nats

  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_CLIENT_NAME=notification-service
      - ORDER_SERVICE_HOST=order-service:50051
    depends_on:
      - order-service
      - nats

volumes:
  mongo_data: